"""initial schema

Revision ID: 941ced96e947
Revises: 
Create Date: 2026-05-13 21:50:25.574641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941ced96e947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('processing_result', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stripe_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stripe_events_received_at'), ['received_at'], unique=False)

    op.create_table('trades',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('trade_type', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('service_area', sa.String(length=200), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('years_active', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('default_deposit_pence', sa.Integer(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('cancellation_policy', sa.String(length=40), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_trades_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_trades_stripe_account_id'), ['stripe_account_id'], unique=False)

    op.create_table('availability_blocks',
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_blocks_block_date'), ['block_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_blocks_trade_id'), ['trade_id'], unique=False)

    op.create_table('availability_rules',
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_rules_trade_id'), ['trade_id'], unique=False)

    op.create_table('services',
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('deposit_pence', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_trade_id'), ['trade_id'], unique=False)

    op.create_table('bookings',
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('service_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_postcode', sa.String(length=16), nullable=False),
    sa.Column('customer_address', sa.String(length=255), nullable=True),
    sa.Column('job_notes', sa.Text(), nullable=True),
    sa.Column('photo_urls', sa.Text(), nullable=True),
    sa.Column('deposit_pence', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'booked', 'on_the_way', 'arrived', 'in_progress', 'complete', 'cancelled', 'no_show', name='booking_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'refunded', 'partial_refund', 'failed', name='payment_status'), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=200), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_stripe_checkout_session_id'), ['stripe_checkout_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index('ix_bookings_trade_start_active', ['trade_id', 'start_at'], unique=True, postgresql_where=sa.text("status IN ('pending_payment','booked','on_the_way','arrived','in_progress','complete')"))
        batch_op.create_index('ix_bookings_trade_status_start', ['trade_id', 'status', 'start_at'], unique=False)

    op.create_table('booking_events',
    sa.Column('booking_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_events_booking_id'), ['booking_id'], unique=False)

    op.create_table('booking_photos',
    sa.Column('booking_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_photos_booking_id'), ['booking_id'], unique=False)

    op.create_table('invoices',
    sa.Column('booking_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'partially_paid', 'paid', 'written_off', 'void', name='invoice_status'), nullable=False),
    sa.Column('subtotal_pence', sa.Integer(), nullable=False),
    sa.Column('vat_pence', sa.Integer(), nullable=False),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('deposit_pence', sa.Integer(), nullable=False),
    sa.Column('amount_paid_pence', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('vat_number', sa.String(length=40), nullable=True),
    sa.Column('vat_rate_bps', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('stripe_payment_link_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_link_url', sa.String(length=500), nullable=True),
    sa.Column('last_chase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chase_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index('ix_invoices_due_date', ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index('ix_invoices_trade_status', ['trade_id', 'status'], unique=False)

    op.create_table('tracking_sessions',
    sa.Column('booking_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'arrived', 'expired', 'stopped', name='tracking_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_sessions_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_sessions_public_token'), ['public_token'], unique=True)

    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('unit_price_pence', sa.Integer(), nullable=False),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('tracking_pings',
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_pings', schema=None) as batch_op:
        batch_op.create_index('ix_tracking_pings_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_pings_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_pings_session_id'))
        batch_op.drop_index('ix_tracking_pings_session_created')

    op.drop_table('tracking_pings')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('tracking_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_sessions_public_token'))
        batch_op.drop_index(batch_op.f('ix_tracking_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_tracking_sessions_booking_id'))

    op.drop_table('tracking_sessions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_trade_status')
        batch_op.drop_index(batch_op.f('ix_invoices_trade_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index('ix_invoices_due_date')
        batch_op.drop_index(batch_op.f('ix_invoices_booking_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('booking_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_photos_booking_id'))

    op.drop_table('booking_photos')
    with op.batch_alter_table('booking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_events_booking_id'))

    op.drop_table('booking_events')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_trade_status_start')
        batch_op.drop_index('ix_bookings_trade_start_active', postgresql_where=sa.text("status IN ('pending_payment','booked','on_the_way','arrived','in_progress','complete')"))
        batch_op.drop_index(batch_op.f('ix_bookings_trade_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_stripe_checkout_session_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_start_at'))
        batch_op.drop_index(batch_op.f('ix_bookings_service_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_reference'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_email'))

    op.drop_table('bookings')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_trade_id'))

    op.drop_table('services')
    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_rules_trade_id'))

    op.drop_table('availability_rules')
    with op.batch_alter_table('availability_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_blocks_trade_id'))
        batch_op.drop_index(batch_op.f('ix_availability_blocks_block_date'))

    op.drop_table('availability_blocks')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_stripe_account_id'))
        batch_op.drop_index(batch_op.f('ix_trades_slug'))
        batch_op.drop_index(batch_op.f('ix_trades_email'))

    op.drop_table('trades')
    with op.batch_alter_table('stripe_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_stripe_events_event_id'))

    op.drop_table('stripe_events')
    # ### end Alembic commands ###
